### ISSUE TITLE
How to not include /usr/lib/.build-id/* into RPM?

### ISSUE THREAD

**Issue by thekvs** [kevinconway/rpmvenv#101]
Hello!

On Fedora Server 33 I get following error while trying  to install RPM:

`file /usr/lib/.build-id/35/4145047f3835a62cb82cb1939f53181bf1ed85 from install of xxx-0.1-1.x86_64 conflicts with file from package python3-3.9.2-1.fc33.x86_64`

Is there a way to not include in the final RPM `/usr/lib/.build-id/` directory? [here](https://access.redhat.com/discussions/5045161) is a more detailed description of issue I face and some discussion.

**Comment by kevinconway** [comment]
There is nothing in `rpmvenv` that is creating or including the `/usr/lib/.build-id` files. It is managed by `rpm` directly. From what I read, you should be able to use the `%define _build_id_links none` macro to disable the feature. https://github.com/danfoster/rpmvenv-macros is a plugin for `rpmvenv` that adds support modifying and setting macros. It is published to [PyPi](https://pypi.org/project/rpmvenv-macros) so you should be able to `pip install rpmvenv-macros` to install it. The README for `rpmvenv-macros` has example JSON configuration for the plugin including an example that disables build-id.

**Comment by thekvs** [comment]
Works perfectly, thanks!
