### ISSUE TITLE
Incompatible with virtualenv 20.8.0

### ISSUE THREAD

**Issue by fsvenson** [kevinconway/rpmvenv#102]
This version of `virtualenv` adds a `nushell` activation script:
https://github.com/pypa/virtualenv/blob/main/docs/changelog.rst#v2080-2021-09-16

The reference to BUILDROOT is not removed from these scripts so `/usr/lib/rpm/check-buildroot` fails after `venvctrl-relocate`. 

It can be worked around by adding `"--activators", "bash,cshell,fish,powershell,python"` to the `python_venv` flags configuration.

**Comment by kevinconway** [comment]
Thanks for opening the issue and sharing a workaround.

The part of `rpmvenv` that is affected by this is another library called [venvctrl](https://github.com/kevinconway/venvctrl). It's the part of the project that handles rewriting elements of the `virtualenv` to make relocation possible.

I've created an issue on `venvcrtrl` [here](https://github.com/kevinconway/venvctrl/issues/19) with a guide on how to add support for the `nushell` activation script. If you or anyone affected by this has time to make a PR then I'd much appreciate it. I'll keep this issue open in the meantime so folks can find the workaround.

**Comment by kevinconway** [comment]
This is fixed in the latest versions of `rpmvenv` and `venvctrl`. Versions `rpmvenv==0.26.0` and `venvctrl==0.5.0` should allow you to remove the workaround.

Thank you again for posting both the issue and the workaround!
