### ISSUE TITLE
Does not work on CentOS 7

### ISSUE THREAD

**Issue by bialix** [kevinconway/rpmvenv#104]
I've created simple smoke test script to test how rpmvenv works and it failed to create an rpm.

```
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenvepiq47s_' /tmp/rpmvenvepiq47s_/SOURCES/package.spec.
The stderr was: b'+ umask 022\n+ cd /tmp/rpmvenvepiq47s_/BUILD\n+ rm -rf \'/tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64/*\'\n+ mkdir -p /tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64//opt/test/smoker/venv\n+ exit 0\n+ umask 022\n+ cd /tmp/rpmvenvepiq47s_/BUILD\n+ \'[\' /tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64 \'!=\' / \']\'\n+ rm -rf /tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64\n++ dirname /tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64\n+ mkdir -p /tmp/rpmvenvepiq47s_/BUILDROOT\n+ mkdir /tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64\n+ virtualenv --always-copy /tmp/rpmvenvepiq47s_/BUILDROOT/python-smoker-1.2.3-1.x86_64//opt/test/smoker/venv\nTraceback (most recent call last):\n  File "/usr/local/bin/virtualenv", line 5, in <module>\n    from virtualenv.__main__ import run_with_catch\nModuleNotFoundError: No module named \'virtualenv\'\nerror: Bad exit status from /var/tmp/rpm-tmp.omHnCd (%install)\n    Bad exit status from /var/tmp/rpm-tmp.omHnCd (%install)\n'.
The stdout was: b'Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.jgbdB7\nExecuting(%install): /bin/sh -e /var/tmp/rpm-tmp.omHnCd\n\n\nRPM build errors:\n'.
```

I think this is the real error:

```
Traceback (most recent call last):
  File "/usr/local/bin/virtualenv", line 5, in <module>
    from virtualenv.__main__ import run_with_catch
ModuleNotFoundError: No module named 'virtualenv'
```

My json config for rpmvenv:

```
{
    "extensions": {
        "enabled": [
            "python_venv",
            "blocks"
        ]
    },
    "core": {
        "group": "Application/System",
        "license": "MIT",
        "name": "python-smoker",
        "summary": "short package summary",
        "version": "1.2.3"
    },
    "python_venv": {
        "name": "venv",
        "path": "/opt/test/smoker"
    },
    "blocks": {
        "desc": [
            "smoking test"
        ]
    }
}
```

Probably due virtualenv version is too new? Can you suggest which virtualenv I should be using?

virtualenv                        20.10.0

**Comment by bialix** [comment]
Downgrading virtualenv to pre 20.8.0 and even to 16.7.8 did not help. The same error.
Virtualenv is installed into system.

**Comment by kevinconway** [comment]
The version of `virtualenv` shouldn't matter much except that the most recent versions require a slight tweak to your config.json to work around a lack of support in `rpmvenv` for `nushell` (https://github.com/kevinconway/rpmvenv/issues/102).

You are right that the issue is that `rpmvenv` cannot find `virtualenv`. One possible cause is if you are using the system packages such as `python-virtualenv`. The system packages usually do not work well with packages installed using pip (https://github.com/kevinconway/rpmvenv#note-system-python). Another possible cause is if you are running `rpmvenv` from _within_ a `virtualenv` but have not installed the `virtualenv` package inside it.

One thing you might also be able to do is get the full path of your `virtualenv` executable using `which virtualenv` and then set that path to the `python_venv.cmd` parameter in your config.json so that rpmvenv does not rely on a configured PATH variable.

**Comment by bialix** [comment]
OK, I've reinstalled all libs in user python lib, starting with your `venvctrl` and ensure it works. Now it works slightly further but anyway fails. I found that without using `--verbose` I can't get normal error reporting.

```
+ cd -
/tmp/rpmvenv8t7vd3b8/BUILD
+ cd /tmp/rpmvenv8t7vd3b8/SOURCES/test-rpm
+ /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/python setup.py install
running install
running build
running build_scripts
creating build
creating build/scripts-3.6
copying smoker.py -> build/scripts-3.6
changing mode of build/scripts-3.6/smoker.py from 664 to 775
running install_scripts
copying build/scripts-3.6/smoker.py -> /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin
changing mode of /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/smoker.py to 775
running install_egg_info
Writing /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/lib/python3.6/site-packages/python_smoker-1.2.3-py3.6.egg-info
+ cd -
/tmp/rpmvenv8t7vd3b8/BUILD
+ find /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64 -name RECORD -exec rm -rf '{}' ';'
+ venvctrl-relocate --source=/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv --destination=/opt/test/smoker/venv
+ find /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/lib -type f -name '*.so'
+ xargs -r strip
+ /usr/lib/rpm/check-buildroot
/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/activate.nu:let virtual-env = "/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv"
/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/activate.nu:alias deactivate = source "/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/deactivate.nu"
Found '/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64' in installed files; aborting
error: Bad exit status from /var/tmp/rpm-tmp.dAGdHk (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.dAGdHk (%install)
There was an error generating the RPM.
The exit code was: 1.
The rpmbuild command was: rpmbuild -ba --define='_topdir /tmp/rpmvenv8t7vd3b8' /tmp/rpmvenv8t7vd3b8/SOURCES/package.spec.
```

Any hints what's wrong now?

**Comment by kevinconway** [comment]
It's complaining that these files have the RPM build root in them:
> /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/activate.nu:let virtual-env = "/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv"
> /tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/activate.nu:alias deactivate = source "/tmp/rpmvenv8t7vd3b8/BUILDROOT/python-smoker-1.2.3-1.x86_64/opt/test/smoker/venv/bin/deactivate.nu"

This is because the most recent versions of `virtualenv` include support for a new shell called `nushell` but `rpmvenv` does not rewrite those shell files yet. You'll need to use the workaround from https://github.com/kevinconway/rpmvenv/issues/102 which is to set a specific list of shells you need that don't include `nushell`.

**Comment by bialix** [comment]
Downgrading virtualenv to 20.7.2 works. Now I can have rpm ))
