### ISSUE TITLE
Warning from pip about installing scripts to venv

### ISSUE THREAD

**Issue by bialix** [kevinconway/rpmvenv#113]
During building of an RPM I've got this warning for several libs that install some scripts to venv/bin:

  WARNING: The script dotenv is installed in '/tmp/rpmvenvvkfptr18/BUILDROOT/myproject-1.x86_64/opt/myproject/bin' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.
 
It will be nice if your tool will use suggested pip option.

**Comment by kevinconway** [comment]
If enough folks raise similar issues then I might add the flag but I'm hesitant to disable warnings by default.

For now, you can add the flag to your project by either adding it to your configuration file like:

```json
{
  "python_venv" {
    "pip_flags": "--no-warn-script-location"
  }
}
```

or you can set the same configuration using a CLI flag like:

```
rpmvenv --python_venv_pip_flags="--no-warn-script-location"
```

See https://github.com/kevinconway/rpmvenv#customizing for all the ways you can customize your configuration and https://github.com/kevinconway/rpmvenv#cli-flags-and-environment-variables for how to use CLI flags or environment variables.

**Comment by bialix** [comment]
Honestly to say - there is no a word about providing options for pip in your doc. So, thank you for detailed example. It's enough for me.

**Comment by bialix** [comment]
Thank you. That helps.
