### ISSUE TITLE
Show progress while building rpm

### ISSUE THREAD

**Issue by fruch** [kevinconway/rpmvenv#15]
something, to let the user know it's working,
also a -v/verbose flag would be nice so we could see what's going on while it's doing it.

**Comment by kevinconway** [comment]
The current behaviour is to capture the stdin/stderr of the process and print it only if there is an exception. However, I  agree there should be an option to view what's happening as it happens. I'll work on it a bit and get an update rolled out.

In the meantime, no news is good news when it comes to the output of the executable.

**Comment by kevinconway** [comment]
I added a `--verbose` flag in #19. It was published to pypi with version 0.9.1.

Using the flag will disable the output capture in favour of streaming it in real-time.

**Comment by fruch** [comment]
Thanks for accepting my suggestion (sorry I didn't had time to put in a
merge request...)
