### ISSUE TITLE
file_permissions and file_extras / spec ordering 

### ISSUE THREAD

**Issue by ariens** [kevinconway/rpmvenv#43]
I have a static directory within a rpmvenv'd packaged web application that I'm copying into the root of the installation dir and I have specified permissons:

```json
{
  "file_permissions": {
    "user": "appuser",
    "group": "appuser",
    "create_user": true,
    "create_group": true
  },
  "file_extras": {
    "files": [
      {
        "src": "app/static",
        "dest": "/opt/app/static"
      }
    ]
  }
}
```
However when installing the RPM the static directory always has the proper owner/group but the other files are occasionally installed as root:root.  

Calling rpmvenv repeatedly with `--spec | grep -A 2  "%files"` shows the `defattr` reference occasionally occurring after the installation root path.  Does order there matter?

Note, I've also removed the `file_extras` block altogether and reproduced intermittently built RPMs that fail to apply the defined permissions.

I'll dig into your code and submit a PR if I can find an easy way to preserve ordering.

**Comment by kevinconway** [comment]
I merged https://github.com/kevinconway/rpmvenv/pull/45 and published a new version on PyPi, 0.15.1, with your change. Thanks for putting in a patch!
