### ISSUE TITLE
Spec file running setup.py even after installting all packages via pip

### ISSUE THREAD

**Issue by Amar-Chaudhari** [kevinconway/rpmvenv#44]
Hi,

`rpmvenv` generated the following spec file from my virtualenv.
After installing all the packages from `requirements.txt`, it seem to be running `setup.py install` from the virtualenv. My virtualenv does not have any setup.py and hence the rpm build fails.

Is there any reason I should be having setup.py in my `virtualenv` directory ?

```
%install
%{venv_cmd} %{venv_dir}
%{venv_pip} -r %{SOURCE0}/requirements.txt
cd %{SOURCE0}
%{venv_python} setup.py install
cd -
```

Trace:

```
+ cd /tmp/rpmvenv1fghuk2r/SOURCES/jupyterhub
+ /tmp/rpmvenv1fghuk2r/BUILDROOT/some-rpm-package-name-1.2.3-1.x86_64//opt/test/jupyterhub/bin/python setup.py install
/tmp/rpmvenv1fghuk2r/BUILDROOT/some-rpm-package-name-1.2.3-1.x86_64//opt/test/jupyterhub/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
error: Bad exit status from /var/tmp/rpm-tmp.3IcTwM (%install)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.3IcTwM (%install)
```

**Comment by kevinconway** [comment]
The rpm builder feature of the tool is not designed to operate on an existing virtualenv. It is intended to operate on Python distributions that have a setup.py file. If you look at the source for this project, as an example, it has a setup.py and several requirements.txt files.

If you give me some more details I may be able to help find a way around your issue. What exactly do you mean when you say "virtualenv directory"? Do you mean you have created something with the virtualenv tool and installed libraries yourself using pip and a requirements.txt file?

**Comment by Amar-Chaudhari** [comment]
@kevinconway  
Sorry if I sound naive, This is my first time building a rpm.  

Yes you guessed it correct !
- I have a created a virtual env with the virtualenvtool
- installed libraries using the pip
- exported all the installed stuff to `requirements.txt` via pip freeze.

And now I am now using the requirements.txt with rpmvenv to build the rpm

**Comment by kevinconway** [comment]
OK, to expand on my earlier comments: The tool is designed specifically to work with Python source projects that follow the typical Python repo organization, [similar to how this guide describes](http://docs.python-guide.org/en/latest/writing/structure/), and have a [setup.py](https://setuptools.readthedocs.io/en/latest/index.html) in the root directory. The intent behind it is to allow people writing services to generate an RPM. The use case of having only a requirements.txt file with nothing else is not something the tool currently supports.

I think we have three options for getting you unblocked from this problem:

The first, and I believe easiest, option is to create a minimal setup.py in the directory with your requirements.txt to satisfy the tool. This would look something like:
```python
from setuptools import setup, find_packages
setup(
    name = "xFAKEPACKAGE",
    version = "0.0.1",
    packages = find_packages(),
)
```
That should trick the tool into thinking you have a source code repository and get it to generate an RPM.

The second option is to make things work by manually editing the spec file and running the rpm commands. You can use the `--spec` flag on the CLI to get the RPM spec file content. From there you can manually edit the content of the file to remove the bits that call setup.py. Then you'll have to set up an rpm packaging workspace and use the rpm tool to generate a package from the spec file. This option requires a decent working knowledge of how RPM and spec files work, though.

A third option is you can make a PR that adds an option to the [`python_venv`](https://github.com/kevinconway/rpmvenv/blob/master/rpmvenv/extensions/python/venv.py) extension that allows you to disable the setup.py interaction.
