### ISSUE TITLE
Files of virtualenv are all unpacked

### ISSUE THREAD

**Issue by FrankCRoth** [kevinconway/rpmvenv#50]
Using the example the rpm is not build because all files from the virtualenv are  unpackaged file(s). I also don't see in the sprec file that they are included. 
What do I mess?

spec-file:

# Macros
%define venv_cmd virtualenv --always-copy
%define venv_name virtualenv
%define venv_install_dir /opt/Scripts/%{venv_name}
%define venv_dir %{buildroot}/%{venv_install_dir}
%define venv_bin %{venv_dir}/bin
%define venv_python %{venv_bin}/python
%define venv_pip %{venv_python} %{venv_bin}/pip install
%define __prelink_undo_cmd %{nil}
# Globals
%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
# Tags
AutoReq: No
AutoProv: No
Name: vmwarescripts
Version: 1.2.3
Release: 1
BuildRoot: %(mktemp -ud %{_tmppath}/%{SOURCE0}-%{version}-%{release}-XXXXXX)
Summary: short package summary
Group: Application/System
License: MIT
Source0: /dev/vmware_scripts
# Blocks
%prep
mkdir -p %{buildroot}/%{venv_install_dir}
rm -rf %{buildroot}/*
%clean
rm -rf %{buildroot}
%files
/%{venv_install_dir}
%description
some long package description
each array element is a new line
%install
%{venv_cmd} %{venv_dir}
%{venv_pip} -r %{SOURCE0}/requirements.txt
cd %{SOURCE0}
%{venv_python} setup.py install
cd -
# RECORD files are used by wheels for checksum. They contain path names which
# match the buildroot and must be removed or the package will fail to build.
find %{buildroot} -name "RECORD" -exec rm -rf {} \;
# Change the virtualenv path to the target installation direcotry.
venvctrl-relocate --source=%{venv_dir} --destination=/%{venv_install_dir}
# Strip native modules as they contain buildroot paths in their debug information
find %{venv_dir}/lib -type f -name "*.so" | xargs -r strip

**Comment by kevinconway** [comment]
The `venv.py` extension handles this for you. It adds

```
%files
/%{venv_install_dir}
```

to the spec which includes all virtualenv related files in the RPM. Can you post the error you are seeing? I don't see anything wrong with the spec.

**Comment by kevinconway** [comment]
I'm closing out the issue since it has gone stale. Please feel free to reopen if needed.
