### ISSUE TITLE
Extra files - Define user/group per mapping

### ISSUE THREAD

**Issue by bernardoVale** [kevinconway/rpmvenv#55]
First of all, thanks you for this project. Really useful, seriously, thanks!

I was wondering if it's possible to define users/groups and permissions per mapping:

```json
"file_extras": {
        "files": [
            {
                "src": "bin/stupidbin",
                "dest": "/usr/local/bin/stupidbin",
                "user": "myapp",
                "group": "appgroup",
                "permissions": "0755"
            }
        ]
    }
```
Is it possible? What do you think? Can we implement that feature?

**Comment by kevinconway** [comment]
I believe it might be possible via the `attr` directive in the `file` block. I'd need to think a bit how this would fit in the current plugins given that it crosses the boundary between the extras plugin and permissions plugin for files.

I'm curious about the use case for this, though. Given that this project is designed to package a virtualenv, what are the circumstances under which you would want parts of the virtualenv to belong to a different user/group than the rest?

**Comment by bernardoVale** [comment]
About the use case. This is not for the virtualenv itself, but only for extra files.

For example, I want to package a config file that should belong to `myapp`, but I also want to package a `init.d` script that should belong to `root`.

```json
"file_extras": {
        "files": [
            {
                "src": "scripts/app",
                "dest": "/etc/init.d/app",
                "user": "root",
                "group": "root",
                "permissions": "0755"
            },
            {
                "src": "config/app.conf",
                "dest": "/etc/app/app.conf,
                "user": "myapp",
                "group": "myapp",
                "permissions": "0640"
            }
        ]
}
```

**Comment by kevinconway** [comment]
Ah, I see. That makes sense. Thinking on it, I realised that I've had this problem before too. I still don't know yet where/how this feature would fit in to the existing code base. In the meantime, though, you can work around the problem by using the `post` segment from the `blocks` plugin.

The `post` block accepts any valid executable shell code and will be executed by the same user/group performing the installation (typically root). In your case you could add `chown root:root /etc/init.d/app` and the permissions will be altered after the file is installed on the system. It's not idea, but that's exactly the method I used to work around the issue. In all of my use cases, there was only one, maybe two, files that needed special permissions and it was faster/easier to use `post` than refactor the plugins.

**Comment by kevinconway** [comment]
I've thought some more on this. As far as I can tell, the common case for this is related to one off files that we need placed elsewhere on the system. I haven't yet found a case where special permissions are needed for more than one or two files and they are usually related to process managers like upstart/systemd. I'm comfortable right now leaving things as they are and relying on the `post` block to handle these cases via a `chown` and `chmod`.

If you hit a case where you need to do this for more than one or two files then reopen the issue and let's talk about it again.
