### ISSUE TITLE
Using rpmvenv without a setup.py file

### ISSUE THREAD

**Issue by coldeasy** [kevinconway/rpmvenv#57]
Hi,

We'd like to use rpmvenv to install a number of packages listed in a requirements file without the need for a setup.py file. The use-case is to install circus in a virtual env and symlink the command line utilities to the usr bin dir. rpmvenv seems ideal for this however at the moment we have to create a dummy setup.py file in order for it to work.
What are your thoughts on making this part optional and allowing just the use of the requirements file?

Thanks
Colin

**Comment by kevinconway** [comment]
There was a similar issue raised in the past here: https://github.com/kevinconway/rpmvenv/issues/44

I'm not against adding an option to disable the `setup.py` usage so long as the default behaviour remains the same as it is today.

**Comment by kevinconway** [comment]
https://github.com/kevinconway/rpmvenv/pull/62 closes this issue.

Thanks, @MeabhG, for taking this on.
