### ISSUE TITLE
no module named site

### ISSUE THREAD

**Issue by sincerywaing** [kevinconway/rpmvenv#79]
I recently want to build an rpm but failed to execute the python in side it. Can you help take a look?

python 2.7.15
build host : ubuntu
install host:centos

I even tried to compile a python and then install everything from scratch. but still report same error.

```
Traceback (most recent call last):
  File "/usr/bin/path/lib/python2.7/site.py", line 171, in <module>
    main()
  File "/usr/bin/path/lib/python2.7/site.py", line 19, in main
    load_host_site()
  File "/usr/bin/path/lib/python2.7/site.py", line 42, in load_host_site
    reload(sys.modules["site"])  # noqa # call system site.py to setup import libraries
ImportError: No module named site
```

**Comment by kevinconway** [comment]
A couple of questions to help debug:
- What versions of ubuntu and centos?
- Do they both have the same version of Python installed?
- Does the exception happen while building the RPM or only when installing?
- What version of `rpmvenv` are you using?
- Are you able to share your JSON configuration file or some form of it that I can use to reproduce the issue?

The stack trace looks a lot like the [system Python issue](https://github.com/kevinconway/rpmvenv#note-system-python) but the solution to that is installing Python from source. It sounds like you've already tried that.

If you can put together a repo that reproduces the issue then I might be able to help debug over my weekend.

**Comment by sincerywaing** [comment]
Thans Kevin!

ubuntu: latest 18.04TLS Server

my target host is actually an old oracle OEL7. but you can use centos as a replacement

no they do not have same version of python. ubuntu is more latest on 2.7.17 or 2.7.15(I complied) and OEL7 is on 2.7.5. should it affect virtualenv?

 no exception happen when building but only when installing.

I think it is the latest rpmvenv. I confirmed with pip -U.

```
{
    "extensions": {
        "enabled": [
            "python_venv",
            "blocks"
        ]
    },
    "core": {
        "group": "Application/System",
        "license": "MIT",
        "name": "venvspecial",
        "summary": "special virtualenv",
        "version": "1.0.2"
    },
    "python_venv": {
        "name": "venvspecial",
        "path": "/usr/bin",
        "pip_flags": "--index-url https://some internal pypi",
        "python": "python2.7"
    },
    "blocks": {
        "desc": [
            "some virtualenv rpm"
        ]
    }
}
```

**Comment by kevinconway** [comment]
@sincerywaing I tried to recreate the issue but I am not able to. I created https://github.com/kevinconway/rpmvenv_issue_79 which has some dockerfiles and scripts to automate building an RPM in Ubuntu 18.04 and install it in both Oracle Linux 7 and Centos 7. It seems to work in both cases. The install works without errors and I am able to source the virtualenv using a shell.

The containers in https://github.com/kevinconway/rpmvenv_issue_79 are using the system Python installations but I checked that they are the same versions you are using (2.7.17 on Ubuntu and 2.7.5 on Oracle/Centos). The patch version difference does not seem to be an issue. It is more likely that there is a difference in the Python installation paths if you compiled your own Python on each system. Some things I recommend trying:

- Check if the `--prefix="/some/path"` flag is the same across all custom Python builds (ex: `./configure --prefix="/my/install/path"`).
- Try using the `--no-site-packages` flag to prevent the virtualenv from containing symlinks to a system Python (ex: `"flags": ["--no-site-packages"],` in the `python_venv` section of the config)

If those don't work then please make a PR to https://github.com/kevinconway/rpmvenv_issue_79 that reproduces the issue. I understand you may be working with internal software that you can't share online but if you can change that repo to include how you're building Python from source and a fake Python package that closely mirrors your internal code install then it might give me more ideas.

**Comment by kevinconway** [comment]
I'm going to close this issue. Please re-open the issue if you find a way for me to reliably reproduce it. I'll leave https://github.com/kevinconway/rpmvenv_issue_79 available for forking in case you're able to use that to reproduce the issue.
