### ISSUE TITLE
rpmvenv incompatible with semver>=2.10.0

### ISSUE THREAD

**Issue by kdoren** [kevinconway/rpmvenv#89]
rpmvenv broke recently (past few months), it throws error in loader.py in validate_extensions.

On one server if works with semver==2.9.1 but breaks with semver==2.10.0 or 2.10.1.
However our build pipeline fails even if semver==2.9.1.

This server is running semver==2.10.0 and fails.  It works with semver==2.9.1

`(env) [centos@deveast-zabbix-proxy1 sbc-api-mpact]$ rpmvenv --verbose sbc-api-mpact-rpmvenv.json
Traceback (most recent call last):
  File "/home/centos/podrouting-test/env/bin/rpmvenv", line 8, in <module>
    sys.exit(main())
  File "/home/centos/podrouting-test/env/lib/python2.7/site-packages/rpmvenv/cli.py", line 119, in main
    extensions_loader.validate_extensions(extensions)
  File "/home/centos/podrouting-test/env/lib/python2.7/site-packages/rpmvenv/extensions/loader.py", line 56, in validate_extensions
    if not semver.match(ext.version, version):
  File "/home/centos/podrouting-test/env/lib/python2.7/site-packages/semver.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/home/centos/podrouting-test/env/lib/python2.7/site-packages/semver.py", line 780, in match
    return ver.match(match_expr)
  File "/home/centos/podrouting-test/env/lib/python2.7/site-packages/semver.py", line 604, in match
    cmp_res = self.compare(match_version)
  File "/home/centos/podrouting-test/env/lib/python2.7/site-packages/semver.py", line 403, in compare
    cls.__name__, type(other)
TypeError: Expected str or VersionInfo instance, but got <type 'unicode'>
`

**Comment by kdoren** [comment]
in our build pipeline:

`Successfully installed Cython-0.28.2 Flask-1.0.2 Flask-Caching-1.4.0 Flask-RESTful-0.3.6 Jinja2-2.10 MarkupSafe-1.0 Werkzeug-0.14.1 aniso8601-1.3.0 boto3-1.10.4 botocore-1.13.4 certifi-2020.4.5.1 chardet-3.0.4 click-6.7 docutils-0.15.2 futures-3.3.0 idna-2.8 itsdangerous-0.24 jmespath-0.9.4 mysql-connector-python-rf-2.2.2 mysqlclient-1.3.12 python-dateutil-2.6.1 pytz-2017.3 redis-2.10.6 requests-2.21.0 s3transfer-0.2.1 semver-2.9.1 six-1.11.0 typing-3.7.4.1 urllib3-1.24.3
+ rpmvenv --verbose sbc-api-mpact-rpmvenv.json
Traceback (most recent call last):
  File "/usr/bin/rpmvenv", line 11, in <module>
    load_entry_point('rpmvenv==0.23.0', 'console_scripts', 'rpmvenv')()
  File "/usr/lib/python2.7/site-packages/rpmvenv/cli.py", line 119, in main
    extensions_loader.validate_extensions(extensions)
  File "/usr/lib/python2.7/site-packages/rpmvenv/extensions/loader.py", line 56, in validate_extensions
    if not semver.match(ext.version, version):
  File "/usr/lib/python2.7/site-packages/semver.py", line 108, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/semver.py", line 813, in match
    return ver.match(match_expr)
  File "/usr/lib/python2.7/site-packages/semver.py", line 637, in match
    cmp_res = self.compare(match_version)
  File "/usr/lib/python2.7/site-packages/semver.py", line 435, in compare
    cls.__name__, type(other)
TypeError: Expected str or VersionInfo instance, but got <type 'unicode'>
script returned exit code 1`

**Comment by kevinconway** [comment]
Thanks for opening the issue!

Something about the output seems off. I can see that you list `2.9.1` as the version but the error output makes references to the latest version (or at least `2.10.0`). For reference, here is the `semver` [code in `master`](https://github.com/python-semver/python-semver/blame/69d1cf205aba68f2e20f0d321d740db5ddce36a1/semver.py#L406) which matches the lines of code referenced in the stack trace and here is the `semver`[ code in 2.9.1](https://github.com/python-semver/python-semver/blame/2.9.1/semver.py#L434) which is different.

If you are using a `virtualenv` to execute `rpmvenv` then it is notable that the version of `semver` being used in the build is actually the one from `site-packages` and not from the `virtualenv`. If you're installing `rpmvenv` and other dependencies and running it on the host then it's possible the `site-packages` has become corrupt for `semver`. I've seen it happen multiple times where you have to repeatedly uninstall a package with `pip uninstall semver` until it finally clears out all the various entries.

**Comment by kdoren** [comment]
Thanks very much for the quick response.  That's an astute observation, I was starting to suspect something like that because of the reference to files in /usr/lib/python2.7/site-packages.  I'll try to figure out why Jenkins is not using the virtualenv even after activating it....   Thaniks!

**Comment by kdoren** [comment]
I fixed the Jenkinsfile issue, problem was that rpmvenv was pip-installed before activating virtualenv which installed latest (incompatible) semver 2.10.1 into system site-packages, breaking rpmvenv,

rpmvenv failed even though (compatible) semver 2.9.1 was installed in virtualenv from requirements.txt.

Moving pip install of rpmvenv to after pip install of requirements.txt got it to build.

There is still an incompatibility between rpmvenv and semver >= 2.10.0, but at the workaround is easy.

Thanks again for you help!

**Comment by kevinconway** [comment]
I'm glad you have work around for the issue. I'll keep this open as a reminder to add a version pinning to prevent recent versions of `semver` from being installed. Thanks again for reporting the issue!

**Comment by kevinconway** [comment]
Finally closing this out with https://github.com/kevinconway/rpmvenv/pull/91. This should prevent any installation from using a version of `sevmer` that is incompatible. Please open another issue if this doesn't help.
