### ISSUE TITLE
requirements.txt includes argparse & ordereddict

### ISSUE THREAD

**Issue by jayvdb** [kevinconway/rpmvenv#96]
requirements.txt either should not include these deps, or require them only on Python 2.6, or 2.7 if the stdlib version isnt acceptable:
- argparse
- ordereddict

**Comment by jayvdb** [comment]
`semver<2.10` should also be limited to Python 2.x where it is needed, and another unpinned `semver` dependency for more recent Pythons.

**Comment by kevinconway** [comment]
This is now resolved in the `2.0.0` release.
