### ISSUE TITLE
How pack application to user virtualenv?

### ISSUE THREAD

**Issue by patsevanton** [kevinconway/rpmvenv#98]
Hello! Thanks for rpmvenv!
I try pack apache-airflow to rpm with all dependencies

```
sudo yum -y install epel-release rpmdevtools wget
sudo yum -y install python3-pip
pip3 install --user rpmvenv
pip3 install --user virtualenv

```
create requirements.txt with my dependencies

```
echo "{}" > conf.json && \
LC_ALL=en_US.UTF-8 rpmvenv conf.json \
  --core_name="apache-airflow" \
  --core_version="1.10.12" \
  --core_license="ASL 2.0" \
  --core_summary="apache-airflow" \
  --extensions_enabled="blocks,python_venv" \
  --python_venv_name="apache-airflow" \
  --blocks_desc="apache-airflow" \
  --python_venv_require_setup_py="false"
```

Pack application by path /usr/share/python/apache-airflow
```
ls /usr/share/python/apache-airflow
LICENSE  bin  etc  lib  lib64  pyvenv.cfg
```

How pack application to user virtualenv? 
How correct change path in python_venv?

**Comment by kevinconway** [comment]
If you are trying to install to `/home/myuser/apache-airflow` then you need to use the `--python_venv_path=/home/mysuer` flag to set the installation root. All of the available virtualenv options are documented here: https://github.com/kevinconway/rpmvenv#python-virtualenv. Installed files default as owned by root so you will also need to enable the `file_permissions` plugin to set the `--file_permissions_user=apache-airflow` and `--file_permissions_group=apache-airflow` options. You can see all of the file permissions options here: https://github.com/kevinconway/rpmvenv#file-permissions.

If you are trying to make an RPM that can install to any user HOME then this is not supported by RPM as far as I know. You can think of `rpmvenv` as a template engine for RPM and `rpmvenv` can only do what RPM supports. Most complicated problems require using custom scripts in the blocks plugin which is documented here: https://github.com/kevinconway/rpmvenv#blocks. If you must use any of the blocks to work around a complicated issue then you may also want to add `--spec` to the flags so you can preview the RPM manifest file before executing it so you can see what code run.
